
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix
          image: shanku1/netflix:latest # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on

